import Navbar from "@/components/navbar";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdn.hugeicons.com/font/hgi-stroke-rounded.css"
          />
        </head>
        <body className={`antialiased`}>
          <Navbar />
          <div className="pt-20 min-h-screen flex flex-col">{children}</div>
        </body>
      </html>
    </SessionProvider>
  );
}
